### ISSUE TITLE
packer.py error

### ISSUE THREAD

**Issue by HehuaTang** [Juniper/contrail-packaging#419]
Hi All,
I use git clone to pull this project to the local machine and want to use packager.py to package the contail-install-package. it reported the following error. 
Anyone could help fix this issue?
  
[root@computer1 build]# ./packager.py --build-id 1234 --sku havana
grep: /home/wangjw/contrail/tools/contrail-packaging/build/.repo/manifest.xml: No such file or directory
cat: /home/wangjw/contrail/tools/contrail-packaging/build/controller/src/base/version.info: No such file or directory
Traceback (most recent call last):
  File "./packager.py", line 360, in <module>
    main()
  File "./packager.py", line 307, in main
    args.parse()
  File "./packager.py", line 150, in parse
    ns_cliargs.depends_package_file = self.get_files_by_pattern(ns_cliargs.depends_package_file, True)
  File "/home/wangjw/contrail/tools/contrail-packaging/build/libs/packager/utils.py", line 264, in get_files_by_pattern
    raise RuntimeError('No Matching files for given pattern (%s)' % patterns)
RuntimeError: No Matchi

**Comment by HehuaTang** [comment]
I have created one .repo directory to solve this issue.

**Comment by fubh** [comment]
hi
I run the command ./packager.py ,so many error ,can you tell me how you solved
